version: '3'
services:
  jupyterlab:
    build:
      context: ./docker
    volumes:
      - ./jupyterlab:/home/jovyan/jupyterlab
    ports:
      - 8888:8888
  build:
    build:
      context: .
    volumes:
      - ./jupyterlab:/home/jovyan/jupyterlab
      - ./conda.recipes:/home/jovyan/jupyterlab/conda.recipes
