{% set name = "jupyterlab-offline" %}
{% set version = "0.31.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../jupyterlab-offline

build:
  number: 0
  script:
    - python -m pip install --no-deps --ignore-installed .
    - python -m jupyterlab_offline.labofflineapp archive
  entry_points:
    - jupyter-laboffline = jupyterlab_offline.labofflineapp:main

test:
  commands:
    - jupyter-laboffline build
    - jupyter-labextension list

requirements:
  build:
    - jupyterlab {{ version }}
    - nodejs
    - python
    - pip
  run:
    - jupyterlab {{ version }}

about:
  home: https://github.com/jupyterlab/jupyterlab
  license: BSD 3-Clause
  summary: (Re)build JupyterLab without a network connection
