{% set name = "jupyterlab-offline-jupyter-widgets-jupyterlab-manager" %}
{% set version = "0.33.2" %}
{% set jlab_min = "0.31" %}
{% set jlab_max = "0.32" %}


package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  script:
    - jupyter laboffline --extension "@jupyter-widgets/jupyterlab-manager@{{ version }}" --name jupyter-widgets-jupyterlab-manager

requirements:
  build:
    - jupyterlab-offline >={{ jlab_min }},<{{ jlab_max }}
    - nodejs
    - python
  run:
    - jupyterlab-offline >={{ jlab_min }},<{{ jlab_max }}
    - nodejs
    - python

about:
  home: https://github.com/jupyter-widgets/ipywidgets
  license: BSD 3-Clause
  summary: Offline assets for building Jupyter Widgets for JupyterLab
