{% set name = "jupyterlab-offline-ipyvolume" %}
{% set version = "0.4.5" %}

{% set jlab_min = "0.31" %}
{% set jlab_max = "0.32" %}

{% set jwm_min = "0.33.2" %}
{% set jwm_max = "0.34" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  script:
    - jupyter-laboffline --extension "ipyvolume@{{ version }}" --name ipyvolume

requirements:
  build:
    - jupyterlab-offline >={{ jlab_min }},<{{ jlab_max }}
    - jupyterlab-offline-jupyter-widgets-jupyterlab-manager >={{ jwm_min }},<{{ jwm_max }}
    - nodejs
    - python
  run:
    - jupyterlab-offline >={{ jlab_min }},<{{ jlab_max }}
    - jupyterlab-offline-jupyter-widgets-jupyterlab-manager >={{ jwm_min }},<{{ jwm_max }}

about:
  home: https://github.com/maartenbreddels/ipyvolume
  license: MIT
  summary: Offline assets for building ipyvolume for JupyterLab
