{% set name = "jupyterlab-offline-jupyter-leaflet" %}
{% set version = "0.7.3" %}

{% set jlab_min = "0.31" %}
{% set jlab_max = "0.32" %}

{% set jwm_min = "0.33.2" %}
{% set jwm_max = "0.34" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  script: jupyter laboffline install jupyter-leaflet {{ version }}

test:
  commands:
    - jupyter laboffline build
    - jupyter-labextension list

requirements:
  build:
    - jupyterlab-offline-jupyter-widgets-jupyterlab-manager >={{ jwm_min }},<{{ jwm_max }}
  run:
    - jupyterlab-offline-jupyter-widgets-jupyterlab-manager >={{ jwm_min }},<{{ jwm_max }}

about:
  home: https://github.com/ellisonbg/ipyleaflet
  license: MIT
  summary: Offline assets for building jupyter-leaflet for JupyterLab
