{% set name = "jupyterlab-offline" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../jupyterlab-offline

build:
  number: 0
  script:
    - python -m pip install --no-deps --ignore-installed .
  entry_points:
    - jupyter-laboffline = jupyterlab_offline.labofflineapp:main

test:
  commands:
    - jupyter laboffline install --baseline
    - jupyter laboffline install "@jupyter-widgets/jupyterlab-manager" "0.33.2"
    - jupyter laboffline build
    - jupyter labextension list

requirements:
  build:
    - jupyterlab
    - nodejs
    - python
    - pip
  run:
    - jupyterlab
    - nodejs
    - python

about:
  home: https://github.com/jupyterlab/jupyterlab
  license: BSD 3-Clause
  summary: (Re)build JupyterLab without a network connection
